artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  # upload to github or google drive. Not using DB or cloud DB bcz this is just the experimenting phase
  source_URL: https://github.com/Krystalli0205/End-to-End-Wine-Quality-Prediction/raw/refs/heads/main/data/winequality-red.csv.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib  # joblib is a serialization library for Python, used to save machine learning models 


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json